openapi: 3.0.2
info:
  description: "Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/)\
    \ or HTML."
  title: Sample API
  version: 0.1.9
servers:
- description: "Optional server description, e.g. Main (production) server"
  url: http://api.example.com/v1
- description: "Optional server description, e.g. Internal staging server for testing"
  url: http://staging-api.example.com
paths:
  /pets:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        "200":
          description: Updated
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    Address:
      properties:
        addressLine1:
          type: string
        addressLine2:
          type: string
        city:
          type: string
        country:
          type: string
        addressTypes:
          items:
            enum:
            - SHIPPING
            - BILLING
            type: string
          type: array
      required:
      - city
      - country
    PetBase:
      properties:
        id:
          readOnly: true
          type: string
        name:
          type: string
        birth_date:
          type: string
        ownerAddress:
          $ref: "#/components/schemas/Address"
      required:
      - name
    Dog:
      allOf:
      - $ref: "#/components/schemas/PetBase"
      - properties:
          pet_type:
            enum:
            - Dog
            type: string
          bark:
            type: boolean
          breed:
            enum:
            - Dingo
            - Husky
            - Retriever
            - Shepherd
            type: string
        required:
        - pet_type
        type: object
    WorkingDog:
      allOf:
      - $ref: "#/components/schemas/Dog"
      - properties:
          pet_type:
            enum:
            - WorkingDog
            type: string
          capabilities:
            items:
              $ref: "#/components/schemas/WorkingDogCapability"
            type: array
        required:
        - capabilities
        - pet_type
        type: object
    WorkingDogCapability:
      enum:
      - Guide
      - Rescue
      - Search
      type: string
    Cat:
      allOf:
      - $ref: "#/components/schemas/PetBase"
      - properties:
          pet_type:
            enum:
            - Cat
            type: string
          hunts:
            type: boolean
          age:
            readOnly: true
            type: integer
        required:
        - pet_type
        type: object
    Goldfish:
      properties:
        pet_type:
          enum:
          - Goldfish
          type: string
        name:
          type: string
        species:
          type: string
      required:
      - pet_type
      type: object
    Pet:
      discriminator:
        propertyName: pet_type
      oneOf:
      - $ref: "#/components/schemas/Cat"
      - $ref: "#/components/schemas/Dog"
      - $ref: "#/components/schemas/WorkingDog"
      - $ref: "#/components/schemas/Goldfish"

