openapi: 3.0.2
info:
  description: "Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/)\
    \ or HTML."
  title: Sample API
  version: 0.1.9
servers:
- description: "Optional server description, e.g. Main (production) server"
  url: http://api.example.com/v1
- description: "Optional server description, e.g. Internal staging server for testing"
  url: http://staging-api.example.com
paths:
  /pets:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        "200":
          description: Updated
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    Address:
      properties:
        addressLine1:
          type: string
        addressLine2:
          type: string
        city:
          type: string
        country:
          type: string
      required:
      - city
      - country
    PetBase:
      properties:
        id:
          readOnly: true
          type: string
        pet_type:
          type: string
        name:
          type: string
        birth_date:
          type: string
        ownerAddress:
          $ref: '#/components/schemas/Address'
      required:
      - pet_type
    Dog:
      allOf:
      - $ref: '#/components/schemas/PetBase'
      - $ref: '#/components/schemas/Dog_allOf'
    Cat:
      allOf:
      - $ref: '#/components/schemas/PetBase'
      - $ref: '#/components/schemas/Cat_allOf'
    Pet:
      discriminator:
        propertyName: pet_type
      oneOf:
      - $ref: '#/components/schemas/Cat'
      - $ref: '#/components/schemas/Dog'
    Dog_allOf:
      discriminator:
        propertyName: pet_type
      properties:
        bark:
          type: boolean
        breed:
          enum:
          - Dingo
          - Husky
          - Retriever
          - Shepherd
          type: string
      type: object
      example: null
    Cat_allOf:
      discriminator:
        propertyName: pet_type
      properties:
        hunts:
          type: boolean
        age:
          readOnly: true
          type: integer
      type: object
      example: null

