/*
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.jhannes.openapi.petstore.api;

import io.github.jhannes.openapi.petstore.model.*;

import io.github.jhannes.openapi.petstore.model.AnyPetDto;

import org.actioncontroller.*;
import org.actioncontroller.json.JsonBody;

import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Consumer;

public interface DefaultApi {
        /**
         * 
         * 
         * @param anyPetDto  (optional)
         */
        @PATCH("/pets")
        public void petsPatch(
                @JsonBody AnyPetDto anyPetDto
        ) throws IOException;
}
