/*
 * Poly API
 * An example of a polymorphic API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: johannes@brodwall.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.poly.api;

import io.github.jhannes.openapi.poly.model.AnyPartyDto;
import io.github.jhannes.openapi.poly.model.CreationErrorDto;
import io.github.jhannes.openapi.poly.model.LogMessageDto;
import java.util.UUID;
import io.github.jhannes.openapi.poly.model.UpdateErrorDto;
import io.github.jhannes.openapi.poly.model.SampleModelData;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.MalformedURLException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new HttpDefaultApi();
    private final SampleModelData sampleData = new SampleModelData(-1);

    public DefaultApiTest() throws MalformedURLException {
    }

    @Test
    public void logMessageTest() throws IOException {
        //LogMessageDto logMessageDto = null;
        //api.logMessage(logMessageDto);
        // TODO: test validations
    }

    @Test
    public void partiesGetTest() throws IOException {
        //AnyPartyDto response = api.partiesGet();
        // TODO: test validations
    }

    @Test
    public void partiesIdPutTest() throws IOException {
        //UUID id = null;
        //AnyPartyDto anyPartyDto = null;
        //api.partiesIdPut(id, anyPartyDto);
        // TODO: test validations
    }

    @Test
    public void partiesPostTest() throws IOException {
        //AnyPartyDto anyPartyDto = null;
        //api.partiesPost(anyPartyDto);
        // TODO: test validations
    }

}
