/*
 * FakeRESTApi.Web V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.fakerestapi.api;

import io.github.jhannes.openapi.fakerestapi.model.UserDto;
import io.github.jhannes.openapi.fakerestapi.model.SampleModelData;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.MalformedURLException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

/**
 * API tests for UsersApi
 */
public class UsersApiTest {

    private final UsersApi api = new HttpUsersApi();
    private final SampleModelData sampleData = new SampleModelData(-1);

    public UsersApiTest() throws MalformedURLException {
    }

    @Test
    public void apiV1UsersGetTest() throws IOException {
        //List<UserDto> response = api.apiV1UsersGet();
        // TODO: test validations
    }

    @Test
    public void apiV1UsersIdDeleteTest() throws IOException {
        //Integer id = null;
        //api.apiV1UsersIdDelete(id);
        // TODO: test validations
    }

    @Test
    public void apiV1UsersIdGetTest() throws IOException {
        //Integer id = null;
        //api.apiV1UsersIdGet(id);
        // TODO: test validations
    }

    @Test
    public void apiV1UsersIdPutTest() throws IOException {
        //Integer id = null;
        //UserDto userDto = null;
        //api.apiV1UsersIdPut(id, userDto);
        // TODO: test validations
    }

    @Test
    public void apiV1UsersPostTest() throws IOException {
        //UserDto userDto = null;
        //api.apiV1UsersPost(userDto);
        // TODO: test validations
    }

}
