/*
 * Poly API
 * An example of a polymorphic API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: johannes@brodwall.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.poly.model;

import java.net.URI;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.function.Function;
import java.util.stream.Collectors;

public interface CreationErrorDto  {
    String getCode();

    static IllegalEmailAddressErrorDto IllegalEmailAddressError() {
        return new IllegalEmailAddressErrorDto().code("IllegalEmailAddressError");
    }
    static DuplicateIdentifierErrorDto DuplicateIdentifierError() {
        return new DuplicateIdentifierErrorDto().code("DuplicateIdentifierError");
    }
    static GeneralErrorDto GeneralError() {
        return new GeneralErrorDto().code("GeneralError");
    }

    static Class<?> getType(String type) {
        switch (type) {
        case "IllegalEmailAddressError":
            return IllegalEmailAddressErrorDto.class;
        case "DuplicateIdentifierError":
            return DuplicateIdentifierErrorDto.class;
        case "GeneralError":
            return GeneralErrorDto.class;
        default:
            throw new IllegalArgumentException("Illegal code " + type);
        }
    }
}

