/*
 * ReqRes API
 * Fake data CRUD API
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.jhannes.openapi.reqres_in.api;

import io.github.jhannes.openapi.reqres_in.model.LoginPost200ResponseDto;
import io.github.jhannes.openapi.reqres_in.model.LoginPost400ResponseDto;
import io.github.jhannes.openapi.reqres_in.model.LoginPostRequestDto;
import io.github.jhannes.openapi.reqres_in.model.RegisterPost200ResponseDto;
import io.github.jhannes.openapi.reqres_in.model.UsersGet200ResponseDto;
import io.github.jhannes.openapi.reqres_in.model.UsersIdGet200ResponseDto;
import io.github.jhannes.openapi.reqres_in.model.UsersIdPut200ResponseDto;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;
import java.util.List;
import java.util.Optional;
import java.util.function.Consumer;

import static java.net.URLEncoder.encode;
import static java.nio.charset.StandardCharsets.UTF_8;

public interface DefaultApi {
    /**
     * Creates a session
     * @param loginPostRequestDto  (required)
     * @return LoginPost200ResponseDto
     */
    LoginPost200ResponseDto loginPost(
            LoginPostRequestDto loginPostRequestDto
    ) throws IOException;
    /**
     * Ends a session
     */
    void logoutPost(
    ) throws IOException;
    /**
     * Creates a user
     * @param loginPostRequestDto  (required)
     * @return RegisterPost200ResponseDto
     */
    RegisterPost200ResponseDto registerPost(
            LoginPostRequestDto loginPostRequestDto
    ) throws IOException;
    /**
     * Fetches a user list
     * @param page  (query) (optional)
     * @param perPage  (query) (optional)
     * @return UsersGet200ResponseDto
     */
    UsersGet200ResponseDto usersGet(
            Optional<Integer> page,
            Optional<Integer> per_page
    ) throws IOException;

    public static class UsersGetQuery {
        private Integer page;

        public UsersGetQuery page(Integer page) {
            this.page = page;
            return this;
        }
        private Integer perPage;

        public UsersGetQuery perPage(Integer perPage) {
            this.perPage = perPage;
            return this;
        }

        public String toUrlEncoded() {
            List<String> parameters = new ArrayList<>();
            if (page != null) {
                parameters.add("page=" + encode(page.toString(), UTF_8));
            }
            if (perPage != null) {
                parameters.add("per_page=" + encode(perPage.toString(), UTF_8));
            }
            return String.join("&", parameters);
        }
    }
    /**
     * Deletes a user
     * @param id  (path) (required)
     */
    void usersIdDelete(
            Integer id
    ) throws IOException;
    /**
     * Fetches a user
     * @param id  (path) (required)
     * @return UsersIdGet200ResponseDto
     */
    UsersIdGet200ResponseDto usersIdGet(
            Integer id
    ) throws IOException;
    /**
     * Updates a user
     * @param id  (path) (required)
     * @return UsersIdPut200ResponseDto
     */
    UsersIdPut200ResponseDto usersIdPatch(
            Integer id
    ) throws IOException;
    /**
     * Updates a user
     * @param id  (path) (required)
     * @return UsersIdPut200ResponseDto
     */
    UsersIdPut200ResponseDto usersIdPut(
            Integer id
    ) throws IOException;
}
