/*
 * Poly API
 * An example of a polymorphic API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: johannes@brodwall.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.poly.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.jhannes.openapi.poly.model.DuplicateIdentifierErrorDto;
import io.github.jhannes.openapi.poly.model.GeneralErrorDto;
import io.github.jhannes.openapi.poly.model.IllegalEmailAddressErrorDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CreationErrorDto
 */


public class CreationErrorDto {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  protected String code;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_IDENTIFIER_VALUE = "identifierValue";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER_VALUE)
  private String identifierValue;

  public static final String SERIALIZED_NAME_ENTITY_TYPE = "entityType";
  @SerializedName(SERIALIZED_NAME_ENTITY_TYPE)
  private String entityType;

  public static final String SERIALIZED_NAME_INPUT_EMAIL_ADDRESS = "inputEmailAddress";
  @SerializedName(SERIALIZED_NAME_INPUT_EMAIL_ADDRESS)
  private String inputEmailAddress;

  public static final String SERIALIZED_NAME_VALID_DOMAINS = "validDomains";
  @SerializedName(SERIALIZED_NAME_VALID_DOMAINS)
  private List<String> validDomains = new ArrayList<String>();

  public CreationErrorDto() {
    this.code = this.getClass().getSimpleName();
  }

  public CreationErrorDto code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(required = true, value = "")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public CreationErrorDto description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(required = true, value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public CreationErrorDto identifierValue(String identifierValue) {
    
    this.identifierValue = identifierValue;
    return this;
  }

   /**
   * Get identifierValue
   * @return identifierValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIdentifierValue() {
    return identifierValue;
  }


  public void setIdentifierValue(String identifierValue) {
    this.identifierValue = identifierValue;
  }


  public CreationErrorDto entityType(String entityType) {
    
    this.entityType = entityType;
    return this;
  }

   /**
   * Get entityType
   * @return entityType
  **/
  @ApiModelProperty(required = true, value = "")

  public String getEntityType() {
    return entityType;
  }


  public void setEntityType(String entityType) {
    this.entityType = entityType;
  }


  public CreationErrorDto inputEmailAddress(String inputEmailAddress) {
    
    this.inputEmailAddress = inputEmailAddress;
    return this;
  }

   /**
   * Get inputEmailAddress
   * @return inputEmailAddress
  **/
  @ApiModelProperty(required = true, value = "")

  public String getInputEmailAddress() {
    return inputEmailAddress;
  }


  public void setInputEmailAddress(String inputEmailAddress) {
    this.inputEmailAddress = inputEmailAddress;
  }


  public CreationErrorDto validDomains(List<String> validDomains) {
    
    this.validDomains = validDomains;
    return this;
  }

  public CreationErrorDto addValidDomainsItem(String validDomainsItem) {
    this.validDomains.add(validDomainsItem);
    return this;
  }

   /**
   * Get validDomains
   * @return validDomains
  **/
  @ApiModelProperty(required = true, value = "")

  public List<String> getValidDomains() {
    return validDomains;
  }


  public void setValidDomains(List<String> validDomains) {
    this.validDomains = validDomains;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreationErrorDto creationError = (CreationErrorDto) o;
    return Objects.equals(this.code, creationError.code) &&
        Objects.equals(this.description, creationError.description) &&
        Objects.equals(this.identifierValue, creationError.identifierValue) &&
        Objects.equals(this.entityType, creationError.entityType) &&
        Objects.equals(this.inputEmailAddress, creationError.inputEmailAddress) &&
        Objects.equals(this.validDomains, creationError.validDomains);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, description, identifierValue, entityType, inputEmailAddress, validDomains);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreationErrorDto {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    identifierValue: ").append(toIndentedString(identifierValue)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    inputEmailAddress: ").append(toIndentedString(inputEmailAddress)).append("\n");
    sb.append("    validDomains: ").append(toIndentedString(validDomains)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

