/*
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.typeHierarchy.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets WorkingDogCapability
 */
@JsonAdapter(WorkingDogCapabilityDto.Adapter.class)
public enum WorkingDogCapabilityDto {
  
  GUIDE("Guide"),
  
  RESCUE("Rescue"),
  
  SEARCH("Search");

  private String value;

  WorkingDogCapabilityDto(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WorkingDogCapabilityDto fromValue(String value) {
    for (WorkingDogCapabilityDto b : WorkingDogCapabilityDto.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<WorkingDogCapabilityDto> {
    @Override
    public void write(final JsonWriter jsonWriter, final WorkingDogCapabilityDto enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WorkingDogCapabilityDto read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WorkingDogCapabilityDto.fromValue(value);
    }
  }
}

