/*
 * Infection Tracker
 * Infection Tracker - A case management system for tracking the spread of diseases
 *
 * The version of the OpenAPI document: 1.0.0-draft
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.jhannes.openapi.infectionTracker.model;


import java.net.URI;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.ZonedDateTime;
import java.time.ZoneId;

import java.util.function.Supplier;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import java.util.UUID;

/**
 * Model tests for Infection Tracker
 */
public class SampleModelData {

    public SampleModelData(Random random) {
        this.random = random;
    }

    public SampleModelData(long seed) {
        this(new Random(seed));
    }

    public CaseWorkerDto sampleCaseWorkerDto(String propertyName) {
        return sampleCaseWorkerDto();
    }

    public CaseWorkerDto sampleCaseWorkerDto() {
        return new CaseWorkerDto()
            .id(randomUUID("id"))
            .fullName(randomString("fullName"))
            .email(randomString("email", "email"))
            .role(sampleUserRoleDto("role"));
    }

    public List<CaseWorkerDto> sampleListOfCaseWorkerDto(String propertyName) {
        return sampleListOfCaseWorkerDto();
    }

    public List<CaseWorkerDto> sampleListOfCaseWorkerDto() {
        return sampleList(() -> sampleCaseWorkerDto());
    }

    public ExposureDto sampleExposureDto(String propertyName) {
        return sampleExposureDto();
    }

    public ExposureDto sampleExposureDto() {
        return new ExposureDto()
            .id(randomUUID("id"))
            .exposedPersonName(randomString("exposedPersonName"))
            .exposedPersonPhoneNumber(randomString("exposedPersonPhoneNumber", "phone"))
            .exposedDate(sampleLocalDate("exposedDate"))
            .exposureLocation(randomString("exposureLocation"))
            .notes(randomString("notes"))
            .caseWorker(randomUUID("caseWorker"))
            .status(sampleExposureDtoStatusEnum("status"))
            .delayAfterInfection(sampleExposureDtoDelayAfterInfectionEnum("delayAfterInfection"));
    }

    public List<ExposureDto> sampleListOfExposureDto(String propertyName) {
        return sampleListOfExposureDto();
    }

    public List<ExposureDto> sampleListOfExposureDto() {
        return sampleList(() -> sampleExposureDto());
    }

    public ExposureDto.StatusEnum sampleExposureDtoStatusEnum(String propertyName) {
        return pickOne(ExposureDto.StatusEnum.values());
    }

    public ExposureDto.DelayAfterInfectionEnum sampleExposureDtoDelayAfterInfectionEnum(String propertyName) {
        return pickOne(ExposureDto.DelayAfterInfectionEnum.values());
    }

    public InfectionDto sampleInfectionDto(String propertyName) {
        return sampleInfectionDto();
    }

    public InfectionDto sampleInfectionDto() {
        return new InfectionDto()
            .id(randomUUID("id"))
            .information(sampleInfectionInformationDto("information"))
            .registeredExposures(sampleListOfExposureDto("registeredExposures"));
    }

    public List<InfectionDto> sampleListOfInfectionDto(String propertyName) {
        return sampleListOfInfectionDto();
    }

    public List<InfectionDto> sampleListOfInfectionDto() {
        return sampleList(() -> sampleInfectionDto());
    }

    public InfectionInformationDto sampleInfectionInformationDto(String propertyName) {
        return sampleInfectionInformationDto();
    }

    public InfectionInformationDto sampleInfectionInformationDto() {
        return new InfectionInformationDto()
            .patientName(randomString("patientName"))
            .patientPhoneNumber(randomString("patientPhoneNumber", "phone"))
            .likelyInfectionDate(sampleLocalDate("likelyInfectionDate"))
            .notes(randomString("notes"));
    }

    public List<InfectionInformationDto> sampleListOfInfectionInformationDto(String propertyName) {
        return sampleListOfInfectionInformationDto();
    }

    public List<InfectionInformationDto> sampleListOfInfectionInformationDto() {
        return sampleList(() -> sampleInfectionInformationDto());
    }

    public UserRoleDto sampleUserRoleDto(String propertyName) {
        return sampleUserRoleDto();
    }

    public UserRoleDto sampleUserRoleDto() {
        return pickOne(UserRoleDto.values());
    }

    public List<UserRoleDto> sampleListOfUserRoleDto(String propertyName) {
        return sampleListOfUserRoleDto();
    }

    public List<UserRoleDto> sampleListOfUserRoleDto() {
        return sampleList(() -> sampleUserRoleDto());
    }

    protected final Random random;
    protected final Map<String, Supplier<String>> dataFormatFactories = new HashMap<>(Map.of(
        "email", this::randomEmail,
        "phone", this::randomPhoneNumber
    ));
    protected final Map<String, Supplier<String>> propertyNameFactories = new HashMap<>(Map.of(
        "givenName", this::randomGivenName,
        "familyName", this::randomFamilyName,
        "personName", this::randomPersonName
    ));

    public <T> List<T> sampleList(Supplier<T> supplier, String propertyName) {
        return sampleList(supplier, propertyName, 1, 4);
    }

    public <T> List<T> sampleList(Supplier<T> supplier) {
        return sampleList(supplier, 1, 4);
    }

    public <T> List<T> sampleList(Supplier<T> supplier, String propertyName, int min, int max) {
        return sampleList(supplier, min, max);
    }

    public <T> List<T> sampleList(Supplier<T> supplier, int min, int max) {
        List<T> result = new ArrayList<>();
        int count = min + random.nextInt(max - min);
        for (int i=0; i<count; i++) {
            result.add(supplier.get());
        }
        return result;
    }

    public <T> Map<String, T> sampleMap(Supplier<T> supplier, String propertyName) {
        return sampleMap(supplier, propertyName, 1, 4);
    }

    public <T> Map<String, T> sampleMap(Supplier<T> supplier, String propertyName, int min, int max) {
        Map<String, T> result = new HashMap<>();
        int count = min + random.nextInt(max - min);
        for (int i=0; i<count; i++) {
            result.put(randomString(propertyName), supplier.get());
        }
        return result;
    }

    public String randomString(String propertyName, String dataFormat) {
        if (dataFormatFactories.containsKey(dataFormat)) {
            return dataFormatFactories.get(dataFormat).get();
        }
        if (propertyNameFactories.containsKey(propertyName)) {
            return propertyNameFactories.get(propertyName).get();
        }
        return "str" + randomUUID(propertyName);
    }

    public String randomString(String propertyName) {
        return randomString(propertyName, null);
    }

    public UUID randomUUID(String propertyName) {
        byte[] bytes = new byte[16];
        random.nextBytes(bytes);
        return UUID.nameUUIDFromBytes(bytes);
    }

    public Long randomLong(String propertyName) {
        return random.nextLong() % 10000L;
    }

    public Integer randomInteger(String propertyName) {
        return random.nextInt(10000);
    }

    public Double randomDouble(String propertyName) {
        return random.nextDouble() * 10000.0;
    }

    public Boolean randomBoolean(String propertyName) {
        return random.nextBoolean();
    }

    public Object randomObject(String propertyName) {
        Map<String, String> result = new HashMap<>();
        result.put(randomString(propertyName + ".key"), randomString(propertyName + ".value"));
        return result;
    }

    public LocalDate sampleLocalDate(String propertyName) {
        return LocalDate.of(2022, 1, 1).plusDays(random.nextInt(1000));
    }

    public LocalTime sampleLocalTime(String propertyName) {
        return LocalTime.of(0, 0).plusMinutes(random.nextInt(24*60));
    }

    public LocalDateTime sampleLocalDateTime(String propertyName) {
        return LocalDateTime.of(
            sampleLocalDate(propertyName), sampleLocalTime(propertyName)
        );
    }

    public ZoneId sampleZoneId(String propertyName) {
        return ZoneId.of(pickOne(ZoneId.getAvailableZoneIds()));
    }

    public ZonedDateTime sampleZonedDateTime(String propertyName) {
        return ZonedDateTime.of(
            sampleLocalDateTime(propertyName), sampleZoneId(propertyName)
        );
    }

    public OffsetDateTime sampleOffsetDateTime(String propertyName) {
        return sampleZonedDateTime(propertyName).toOffsetDateTime();
    }

    public Instant sampleInstant(String propertyName) {
        return sampleZonedDateTime(propertyName).toInstant();
    }

    public URI randomURI(String propertyName) {
        return asURI("https://" + randomDomainName());
    }

    public String randomDomainName() {
        return pickOne(List.of("a", "b", "c")) +
            ".example." +
            pickOne(List.of("com", "net", "io"));
    }

    public String randomEmail() {
        return (
            randomGivenName().toLowerCase() +
            "." +
            randomFamilyName().toLowerCase() +
            "@" +
            randomDomainName()
        );
    }

    public String randomPersonName() {
        return randomGivenName() + " " + randomFamilyName();
    }

    public String randomGivenName() {
        return pickOne(List.of("James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Linda"));
    }

    public String randomFamilyName() {
        return pickOne(List.of("Smith", "Williams", "Johnson", "Jones", "Brown", "Davis", "Wilson"));
    }

    public String randomPhoneNumber() {
        return "636-555-" + (1000 + random.nextInt(9000));
    }

    public <T> T pickOne(T[] alternatives) {
        return alternatives[random.nextInt(alternatives.length)];
    }

    public <T> T pickOne(List<T> alternatives) {
        return alternatives.get(random.nextInt(alternatives.size()));
    }

    public <T> T pickOne(Set<T> alternatives) {
        return pickOne(new ArrayList<>(alternatives));
    }

    public static URI asURI(String uri) {
        try {
            return new URI(uri);
        } catch (java.net.URISyntaxException e) {
            throw new RuntimeException(e);
        }
    }

}
