/*
 * Open ID Connect
 * Open ID Connect Discovery
 *
 * The version of the OpenAPI document: 1.0.0-draft
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.openid_configuration.api;

import io.github.jhannes.openapi.openid_configuration.model.GrantTypeDto;
import io.github.jhannes.openapi.openid_configuration.model.OauthErrorDto;
import io.github.jhannes.openapi.openid_configuration.model.ResponseTypeDto;
import io.github.jhannes.openapi.openid_configuration.model.TokenResponseDto;
import java.net.URI;
import io.github.jhannes.openapi.openid_configuration.model.UserinfoDto;
import io.github.jhannes.openapi.openid_configuration.model.SampleModelData;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.MalformedURLException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

/**
 * API tests for IdentityProviderApi
 */
public class IdentityProviderApiTest {

    private final IdentityProviderApi api = new HttpIdentityProviderApi();
    private final SampleModelData sampleData = new SampleModelData(-1);

    public IdentityProviderApiTest() throws MalformedURLException {
    }

    @Test
    public void authorizationTest() throws IOException {
        //ResponseTypeDto responseType = null;
        //String clientId = null;
        //URI redirectUri = null;
        //String responseMode = null;
        //String state = null;
        //String scope = null;
        //String loginHint = null;
        //List<String> prompt = null;
        //List<String> acrValues = null;
        //String nonce = null;
        //String display = null;
        //api.authorization(responseType, clientId, redirectUri, responseMode, state, scope, loginHint, prompt, acrValues, nonce, display);
        // TODO: test validations
    }

    @Test
    public void fetchTokenTest() throws IOException {
        //GrantTypeDto grantType = null;
        //String clientId = null;
        //String code = null;
        //String authorization = null;
        //String clientSecret = null;
        //URI redirectUri = null;
        //String refreshToken = null;
        //String subjectToken = null;
        //String audience = null;
        //TokenResponseDto response = api.fetchToken(grantType, clientId, code, authorization, clientSecret, redirectUri, refreshToken, subjectToken, audience);
        // TODO: test validations
    }

    @Test
    public void getUserinfoTest() throws IOException {
        //String authorization = null;
        //UserinfoDto response = api.getUserinfo(authorization);
        // TODO: test validations
    }

}
