/*
 * ReqRes API
 * Fake data CRUD API
 *
 * The version of the OpenAPI document: 1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.reqres_in.model;

import java.io.File;
import java.net.URI;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
* UserDto
*/
public class UserDto {

    private Integer id = null;

    private String email = null;

    private String first_name = null;

    private String last_name = null;

    private String avatar = null;

    public static String[] readOnlyFields() {
        return new String[] {
        };
    }

    public static String[] writeOnlyFields() {
        return new String[] {
        };
    }

    public static String[] requiredFields() {
        return new String[] {
        };
    }

    public List<String> missingRequiredFields() {
        List<String> result = new ArrayList<>();
        return result;
    }

    public void readOnlyFieldsWithValue(List<String> result) {
    }

    public <T extends UserDto> T copyTo(T target) {
        if (this.getId() != null) target.setId(this.getId());
        if (this.getEmail() != null) target.setEmail(this.getEmail());
        if (this.getFirstName() != null) target.setFirstName(this.getFirstName());
        if (this.getLastName() != null) target.setLastName(this.getLastName());
        if (this.getAvatar() != null) target.setAvatar(this.getAvatar());
        return target;
    }

    private boolean isMissing(String s) {
        return s == null || s.isEmpty();
    }

    private boolean isMissing(List<?> list) {
        return list == null;
    }

    private boolean isMissing(Object s) {
        return s == null;
    }


    /**
     * Get id
     * @return id
     */
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public UserDto id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get email
     * @return email
     */
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public UserDto email(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get first_name
     * @return first_name
     */
    public String getFirstName() {
        return first_name;
    }

    public void setFirstName(String firstName) {
        this.first_name = firstName;
    }

    public UserDto firstName(String firstName) {
        this.first_name = firstName;
        return this;
    }

    /**
     * Get last_name
     * @return last_name
     */
    public String getLastName() {
        return last_name;
    }

    public void setLastName(String lastName) {
        this.last_name = lastName;
    }

    public UserDto lastName(String lastName) {
        this.last_name = lastName;
        return this;
    }

    /**
     * Get avatar
     * @return avatar
     */
    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public UserDto avatar(String avatar) {
        this.avatar = avatar;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserDto user = (UserDto) o;
        return Objects.equals(this.getId(), user.getId()) &&
                Objects.equals(this.getEmail(), user.getEmail()) &&
                Objects.equals(this.getFirstName(), user.getFirstName()) &&
                Objects.equals(this.getLastName(), user.getLastName()) &&
                Objects.equals(this.getAvatar(), user.getAvatar());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getEmail(), getFirstName(), getLastName(), getAvatar());
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserDto {\n");
        sb.append("    id: ").append(toIndentedString(getId())).append("\n");
        sb.append("    email: ").append(toIndentedString(getEmail())).append("\n");
        sb.append("    first_name: ").append(toIndentedString(getFirstName())).append("\n");
        sb.append("    last_name: ").append(toIndentedString(getLastName())).append("\n");
        sb.append("    avatar: ").append(toIndentedString(getAvatar())).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

