/*
 * FakeRESTApi.Web V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.jhannes.openapi.fakerestapi.api;

import io.github.jhannes.openapi.fakerestapi.model.AuthorDto;

import java.io.IOException;
import java.util.Map;
import java.util.List;
import java.util.Optional;
import java.util.function.Consumer;

public interface AuthorsApi {
    /**
     * @param idBook  (path) (required)
     * @return List&lt;AuthorDto&gt;
     */
    List<AuthorDto> apiV1AuthorsAuthorsBooksIdBookGet(
            Integer idBook
    ) throws IOException;
    /**
     * @return List&lt;AuthorDto&gt;
     */
    List<AuthorDto> apiV1AuthorsGet(
    ) throws IOException;
    /**
     * @param id  (path) (required)
     */
    void apiV1AuthorsIdDelete(
            Integer id
    ) throws IOException;
    /**
     * @param id  (path) (required)
     * @return AuthorDto
     */
    AuthorDto apiV1AuthorsIdGet(
            Integer id
    ) throws IOException;
    /**
     * @param id  (path) (required)
     * @param authorDto  (optional)
     * @return AuthorDto
     */
    AuthorDto apiV1AuthorsIdPut(
            Integer id,
            AuthorDto authorDto
    ) throws IOException;
    /**
     * @param authorDto  (optional)
     * @return AuthorDto
     */
    AuthorDto apiV1AuthorsPost(
            AuthorDto authorDto
    ) throws IOException;
}
