/*
 * FakeRESTApi.Web V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.jhannes.openapi.fakerestapi.api;

import io.github.jhannes.openapi.fakerestapi.model.BookDto;

import java.io.IOException;
import java.util.Map;
import java.util.List;
import java.util.Optional;
import java.util.function.Consumer;

public interface BooksApi {
    /**
     * @return List&lt;BookDto&gt;
     */
    List<BookDto> apiV1BooksGet(
    ) throws IOException;
    /**
     * @param id  (path) (required)
     */
    void apiV1BooksIdDelete(
            Integer id
    ) throws IOException;
    /**
     * @param id  (path) (required)
     * @return BookDto
     */
    BookDto apiV1BooksIdGet(
            Integer id
    ) throws IOException;
    /**
     * @param id  (path) (required)
     * @param bookDto  (optional)
     */
    void apiV1BooksIdPut(
            Integer id,
            BookDto bookDto
    ) throws IOException;
    /**
     * @param bookDto  (optional)
     */
    void apiV1BooksPost(
            BookDto bookDto
    ) throws IOException;
}
