/*
 * FakeRESTApi.Web V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.jhannes.openapi.fakerestapi.api;

import io.github.jhannes.openapi.fakerestapi.model.CoverPhotoDto;

import java.io.IOException;
import java.util.Map;
import java.util.List;
import java.util.Optional;

public interface CoverPhotosApi {
    /**
     * @param idBook  (path) (required)
     * @return List&lt;CoverPhotoDto&gt;
     */
    List<CoverPhotoDto> apiV1CoverPhotosBooksCoversIdBookGet(
            Integer idBook
    ) throws IOException;
    /**
     * @return List&lt;CoverPhotoDto&gt;
     */
    List<CoverPhotoDto> apiV1CoverPhotosGet(
    ) throws IOException;
    /**
     * @param id  (path) (required)
     */
    void apiV1CoverPhotosIdDelete(
            Integer id
    ) throws IOException;
    /**
     * @param id  (path) (required)
     * @return CoverPhotoDto
     */
    CoverPhotoDto apiV1CoverPhotosIdGet(
            Integer id
    ) throws IOException;
    /**
     * @param id  (path) (required)
     * @param coverPhotoDto  (optional)
     * @return CoverPhotoDto
     */
    CoverPhotoDto apiV1CoverPhotosIdPut(
            Integer id,
            CoverPhotoDto coverPhotoDto
    ) throws IOException;
    /**
     * @param coverPhotoDto  (optional)
     * @return CoverPhotoDto
     */
    CoverPhotoDto apiV1CoverPhotosPost(
            CoverPhotoDto coverPhotoDto
    ) throws IOException;
}
