/*
 * FakeRESTApi.Web V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.jhannes.openapi.fakerestapi.api;

import io.github.jhannes.openapi.fakerestapi.model.*;

import io.github.jhannes.openapi.fakerestapi.model.CoverPhotoDto;

import org.actioncontroller.actions.*;
import org.actioncontroller.values.*;
import org.actioncontroller.values.json.JsonBody;

import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Consumer;

public interface CoverPhotosApi {
    /**
     * @param idBook  (required)
     * @return List&lt;CoverPhotoDto&gt;
     */
    @GET("/api/v1/CoverPhotos/books/covers/{idBook}")
    @JsonBody
    public List<CoverPhotoDto> apiV1CoverPhotosBooksCoversIdBookGet(
            @PathParam("idBook") Integer idBook
    ) throws IOException;
    /**
     * @return List&lt;CoverPhotoDto&gt;
     */
    @GET("/api/v1/CoverPhotos")
    @JsonBody
    public List<CoverPhotoDto> apiV1CoverPhotosGet(
    ) throws IOException;
    /**
     * @param id  (required)
     */
    @DELETE("/api/v1/CoverPhotos/{id}")
    public void apiV1CoverPhotosIdDelete(
            @PathParam("id") Integer id
    ) throws IOException;
    /**
     * @param id  (required)
     * @return CoverPhotoDto
     */
    @GET("/api/v1/CoverPhotos/{id}")
    @JsonBody
    public CoverPhotoDto apiV1CoverPhotosIdGet(
            @PathParam("id") Integer id
    ) throws IOException;
    /**
     * @param id  (required)
     * @param coverPhotoDto  (optional)
     * @return CoverPhotoDto
     */
    @PUT("/api/v1/CoverPhotos/{id}")
    @JsonBody
    public CoverPhotoDto apiV1CoverPhotosIdPut(
            @PathParam("id") Integer id,
            @JsonBody CoverPhotoDto coverPhotoDto
    ) throws IOException;
    /**
     * @param coverPhotoDto  (optional)
     * @return CoverPhotoDto
     */
    @POST("/api/v1/CoverPhotos")
    @JsonBody
    public CoverPhotoDto apiV1CoverPhotosPost(
            @JsonBody CoverPhotoDto coverPhotoDto
    ) throws IOException;
}
