/*
 * Health API
 * Returns the status of the service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.serverHealth.model;

import java.io.File;
import java.net.URI;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
* DataSourceHealthDetailsDto
*/
public class DataSourceHealthDetailsDto implements HealthDetailsDto {

    private String type = "DataSourceHealthDetails";

    private String url = null;

    private OffsetDateTime lastAliveTime = null;

    private ExceptionDto lastFailureException = null;

    public static String[] readOnlyFields() {
        return new String[] {
        };
    }

    public static String[] writeOnlyFields() {
        return new String[] {
        };
    }

    public static String[] requiredFields() {
        return new String[] {
                "type",
        };
    }

    public List<String> missingRequiredFields() {
        List<String> result = new ArrayList<>();
        if (isMissing(getType())) result.add("type");
        return result;
    }

    public void readOnlyFieldsWithValue(List<String> result) {
        if (lastFailureException != null) {
            lastFailureException.readOnlyFieldsWithValue(result);
        }
    }

    public <T extends DataSourceHealthDetailsDto> T copyTo(T target) {
        if (this.getType() != null) target.setType(this.getType());
        if (this.getUrl() != null) target.setUrl(this.getUrl());
        if (this.getLastAliveTime() != null) target.setLastAliveTime(this.getLastAliveTime());
        if (this.getLastFailureException() != null) target.setLastFailureException(this.getLastFailureException());
        return target;
    }

    private boolean isMissing(String s) {
        return s == null || s.isEmpty();
    }

    private boolean isMissing(List<?> list) {
        return list == null;
    }

    private boolean isMissing(Object s) {
        return s == null;
    }


    /**
     * Get type
     * @return type
     */
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public DataSourceHealthDetailsDto type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get url
     * @return url
     */
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public DataSourceHealthDetailsDto url(String url) {
        this.url = url;
        return this;
    }

    /**
     * Get lastAliveTime
     * @return lastAliveTime
     */
    public OffsetDateTime getLastAliveTime() {
        return lastAliveTime;
    }

    public void setLastAliveTime(OffsetDateTime lastAliveTime) {
        this.lastAliveTime = lastAliveTime;
    }

    public DataSourceHealthDetailsDto lastAliveTime(OffsetDateTime lastAliveTime) {
        this.lastAliveTime = lastAliveTime;
        return this;
    }

    /**
     * Get lastFailureException
     * @return lastFailureException
     */
    public ExceptionDto getLastFailureException() {
        return lastFailureException;
    }

    public void setLastFailureException(ExceptionDto lastFailureException) {
        this.lastFailureException = lastFailureException;
    }

    public DataSourceHealthDetailsDto lastFailureException(ExceptionDto lastFailureException) {
        this.lastFailureException = lastFailureException;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DataSourceHealthDetailsDto dataSourceHealthDetails = (DataSourceHealthDetailsDto) o;
        return Objects.equals(this.getType(), dataSourceHealthDetails.getType()) &&
                Objects.equals(this.getUrl(), dataSourceHealthDetails.getUrl()) &&
                Objects.equals(this.getLastAliveTime(), dataSourceHealthDetails.getLastAliveTime()) &&
                Objects.equals(this.getLastFailureException(), dataSourceHealthDetails.getLastFailureException());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getType(), getUrl(), getLastAliveTime(), getLastFailureException());
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("DataSourceHealthDetailsDto {\n");
        sb.append("    type: ").append(toIndentedString(getType())).append("\n");
        sb.append("    url: ").append(toIndentedString(getUrl())).append("\n");
        sb.append("    lastAliveTime: ").append(toIndentedString(getLastAliveTime())).append("\n");
        sb.append("    lastFailureException: ").append(toIndentedString(getLastFailureException())).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

