/*
 * Health API
 * Returns the status of the service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.serverHealth.model;

import java.io.File;
import java.net.URI;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
* HealthComponentFailureDetailsDto
*/
public class HealthComponentFailureDetailsDto implements HealthDetailsDto {

    private String type = "HealthComponentFailureDetails";

    private ExceptionDto exception = null;

    public static String[] readOnlyFields() {
        return new String[] {
        };
    }

    public static String[] writeOnlyFields() {
        return new String[] {
        };
    }

    public static String[] requiredFields() {
        return new String[] {
                "type",
        };
    }

    public List<String> missingRequiredFields() {
        List<String> result = new ArrayList<>();
        if (isMissing(getType())) result.add("type");
        return result;
    }

    public void readOnlyFieldsWithValue(List<String> result) {
        if (exception != null) {
            exception.readOnlyFieldsWithValue(result);
        }
    }

    public <T extends HealthComponentFailureDetailsDto> T copyTo(T target) {
        if (this.getType() != null) target.setType(this.getType());
        if (this.getException() != null) target.setException(this.getException());
        return target;
    }

    private boolean isMissing(String s) {
        return s == null || s.isEmpty();
    }

    private boolean isMissing(List<?> list) {
        return list == null;
    }

    private boolean isMissing(Object s) {
        return s == null;
    }


    /**
     * Get type
     * @return type
     */
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public HealthComponentFailureDetailsDto type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get exception
     * @return exception
     */
    public ExceptionDto getException() {
        return exception;
    }

    public void setException(ExceptionDto exception) {
        this.exception = exception;
    }

    public HealthComponentFailureDetailsDto exception(ExceptionDto exception) {
        this.exception = exception;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        HealthComponentFailureDetailsDto healthComponentFailureDetails = (HealthComponentFailureDetailsDto) o;
        return Objects.equals(this.getType(), healthComponentFailureDetails.getType()) &&
                Objects.equals(this.getException(), healthComponentFailureDetails.getException());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getType(), getException());
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("HealthComponentFailureDetailsDto {\n");
        sb.append("    type: ").append(toIndentedString(getType())).append("\n");
        sb.append("    exception: ").append(toIndentedString(getException())).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

