/*
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.typeHierarchy.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DogAllOfDto
 */
public class DogAllOfDtoTest {
    private final DogAllOfDto model = new DogAllOfDto();

    /**
     * Model tests for DogAllOfDto
     */
    @Test
    public void testDogAllOfDto() {
        // TODO: test DogAllOfDto
    }

    /**
     * Test the property 'petType'
     */
    @Test
    public void petTypeTest() {
        // TODO: test petType
    }

    /**
     * Test the property 'bark'
     */
    @Test
    public void barkTest() {
        // TODO: test bark
    }

    /**
     * Test the property 'breed'
     */
    @Test
    public void breedTest() {
        // TODO: test breed
    }

}
