/*
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.typeHierarchy.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.jhannes.openapi.typeHierarchy.model.AddressDto;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DogDto
 */
class DogDtoTest {
    private final DogDto model = new DogDto();

    /**
     * Model tests for DogDto
     */
    @Test
    void testDogDto() {
        // TODO: test DogDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'birthDate'
     */
    @Test
    void birthDateTest() {
        // TODO: test birthDate
    }

    /**
     * Test the property 'ownerAddress'
     */
    @Test
    void ownerAddressTest() {
        // TODO: test ownerAddress
    }

    /**
     * Test the property 'petType'
     */
    @Test
    void petTypeTest() {
        // TODO: test petType
    }

    /**
     * Test the property 'bark'
     */
    @Test
    void barkTest() {
        // TODO: test bark
    }

    /**
     * Test the property 'breed'
     */
    @Test
    void breedTest() {
        // TODO: test breed
    }

}
