/*
 * Sample API
 * A small example to demonstrate individual problems
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.bigExample.api;

import io.github.jhannes.openapi.bigExample.ApiException;
import java.time.LocalDate;
import io.github.jhannes.openapi.bigExample.model.PetDto;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addPetTest() throws ApiException {
        //
        //UUID storeId = null;
        //
        //PetDto petDto = null;
        //
        //api.addPet(storeId, petDto);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addPetWithFormTest() throws ApiException {
        //
        //UUID petId = null;
        //
        //String name = null;
        //
        //String status = null;
        //
        //api.addPetWithForm(petId, name, status);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listPetsTest() throws ApiException {
        //
        //UUID storeId = null;
        //
        //List<String> status = null;
        //
        //List<String> tags = null;
        //
        //LocalDate bornAfter = null;
        //
        //PetDto response = api.listPets(storeId, status, tags, bornAfter);

        // TODO: test validations
    }
}
