/*
 * Open ID Connect
 * Open ID Connect Discovery
 *
 * The version of the OpenAPI document: 1.0.0-draft
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.openid_configuration.model;

import java.io.File;
import java.net.URI;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
* DiscoveryDocumentDto
*/
public class DiscoveryDocumentDto {

    private String issuer;

    private URI authorization_endpoint;

    private URI token_endpoint;

    private URI userinfo_endpoint = null;

    private URI end_session_endpoint = null;

    private URI jwks_uri = null;

    private Set<GrantTypeDto> grant_types_supported = null;

    private Set<String> scopes_supported = null;

    private Set<String> claims_supported = null;

    private Set<ResponseTypeDto> response_types_supported = new LinkedHashSet<>();

    /**
     * Gets or Sets responseModesSupported
     */
    public enum ResponseModesSupportedEnum {

        query("query"),
        fragment("fragment"),
        form_post("form_post");

        private String value;

        ResponseModesSupportedEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static ResponseModesSupportedEnum fromValue(String text) {
            for (ResponseModesSupportedEnum b : ResponseModesSupportedEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + text + "'");
        }
    }

    private Set<ResponseModesSupportedEnum> response_modes_supported = null;

    /**
     * Gets or Sets subjectTypesSupported
     */
    public enum SubjectTypesSupportedEnum {

        pairwise("pairwise"),
        _public("public");

        private String value;

        SubjectTypesSupportedEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static SubjectTypesSupportedEnum fromValue(String text) {
            for (SubjectTypesSupportedEnum b : SubjectTypesSupportedEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + text + "'");
        }
    }

    private Set<SubjectTypesSupportedEnum> subject_types_supported = null;

    /**
     * Gets or Sets codeChallengeMethodsSupported
     */
    public enum CodeChallengeMethodsSupportedEnum {

        S256("S256"),
        plain("plain");

        private String value;

        CodeChallengeMethodsSupportedEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static CodeChallengeMethodsSupportedEnum fromValue(String text) {
            for (CodeChallengeMethodsSupportedEnum b : CodeChallengeMethodsSupportedEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + text + "'");
        }
    }

    private Set<CodeChallengeMethodsSupportedEnum> code_challenge_methods_supported = null;

    /**
     * Gets or Sets idTokenSigningAlgValuesSupported
     */
    public enum IdTokenSigningAlgValuesSupportedEnum {

        RS256("RS256");

        private String value;

        IdTokenSigningAlgValuesSupportedEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static IdTokenSigningAlgValuesSupportedEnum fromValue(String text) {
            for (IdTokenSigningAlgValuesSupportedEnum b : IdTokenSigningAlgValuesSupportedEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + text + "'");
        }
    }

    private List<IdTokenSigningAlgValuesSupportedEnum> id_token_signing_alg_values_supported = null;

    private String x_sso_frame = null;

    public static String[] readOnlyFields() {
        return new String[] {
        };
    }

    public static String[] writeOnlyFields() {
        return new String[] {
        };
    }

    public static String[] requiredFields() {
        return new String[] {
                "issuer",
                "authorization_endpoint",
                "token_endpoint",
                "response_types_supported",
        };
    }

    public List<String> missingRequiredFields() {
        List<String> result = new ArrayList<>();
        if (isMissing(getIssuer())) result.add("issuer");
        if (isMissing(getAuthorizationEndpoint())) result.add("authorization_endpoint");
        if (isMissing(getTokenEndpoint())) result.add("token_endpoint");
        if (isMissing(getResponseTypesSupported())) result.add("response_types_supported");
        return result;
    }

    public void readOnlyFieldsWithValue(List<String> result) {
    }

    public <T extends DiscoveryDocumentDto> T copyTo(T target) {
        if (this.getIssuer() != null) target.setIssuer(this.getIssuer());
        if (this.getAuthorizationEndpoint() != null) target.setAuthorizationEndpoint(this.getAuthorizationEndpoint());
        if (this.getTokenEndpoint() != null) target.setTokenEndpoint(this.getTokenEndpoint());
        if (this.getUserinfoEndpoint() != null) target.setUserinfoEndpoint(this.getUserinfoEndpoint());
        if (this.getEndSessionEndpoint() != null) target.setEndSessionEndpoint(this.getEndSessionEndpoint());
        if (this.getJwksUri() != null) target.setJwksUri(this.getJwksUri());
        if (this.getGrantTypesSupported() != null) target.setGrantTypesSupported(this.getGrantTypesSupported());
        if (this.getScopesSupported() != null) target.setScopesSupported(this.getScopesSupported());
        if (this.getClaimsSupported() != null) target.setClaimsSupported(this.getClaimsSupported());
        if (this.getResponseTypesSupported() != null) target.setResponseTypesSupported(this.getResponseTypesSupported());
        if (this.getResponseModesSupported() != null) target.setResponseModesSupported(this.getResponseModesSupported());
        if (this.getSubjectTypesSupported() != null) target.setSubjectTypesSupported(this.getSubjectTypesSupported());
        if (this.getCodeChallengeMethodsSupported() != null) target.setCodeChallengeMethodsSupported(this.getCodeChallengeMethodsSupported());
        if (this.getIdTokenSigningAlgValuesSupported() != null) target.setIdTokenSigningAlgValuesSupported(this.getIdTokenSigningAlgValuesSupported());
        if (this.getxSsoFrame() != null) target.setxSsoFrame(this.getxSsoFrame());
        return target;
    }

    private boolean isMissing(String s) {
        return s == null || s.isEmpty();
    }

    private boolean isMissing(List<?> list) {
        return list == null;
    }

    private boolean isMissing(Object s) {
        return s == null;
    }


    /**
     * Get issuer
     * @return issuer
     */
    public String getIssuer() {
        return issuer;
    }

    public void setIssuer(String issuer) {
        this.issuer = issuer;
    }

    public DiscoveryDocumentDto issuer(String issuer) {
        this.issuer = issuer;
        return this;
    }

    /**
     * Get authorization_endpoint
     * @return authorization_endpoint
     */
    public URI getAuthorizationEndpoint() {
        return authorization_endpoint;
    }

    public void setAuthorizationEndpoint(URI authorizationEndpoint) {
        this.authorization_endpoint = authorizationEndpoint;
    }

    public DiscoveryDocumentDto authorizationEndpoint(URI authorizationEndpoint) {
        this.authorization_endpoint = authorizationEndpoint;
        return this;
    }

    /**
     * Get token_endpoint
     * @return token_endpoint
     */
    public URI getTokenEndpoint() {
        return token_endpoint;
    }

    public void setTokenEndpoint(URI tokenEndpoint) {
        this.token_endpoint = tokenEndpoint;
    }

    public DiscoveryDocumentDto tokenEndpoint(URI tokenEndpoint) {
        this.token_endpoint = tokenEndpoint;
        return this;
    }

    /**
     * Get userinfo_endpoint
     * @return userinfo_endpoint
     */
    public URI getUserinfoEndpoint() {
        return userinfo_endpoint;
    }

    public void setUserinfoEndpoint(URI userinfoEndpoint) {
        this.userinfo_endpoint = userinfoEndpoint;
    }

    public DiscoveryDocumentDto userinfoEndpoint(URI userinfoEndpoint) {
        this.userinfo_endpoint = userinfoEndpoint;
        return this;
    }

    /**
     * Get end_session_endpoint
     * @return end_session_endpoint
     */
    public URI getEndSessionEndpoint() {
        return end_session_endpoint;
    }

    public void setEndSessionEndpoint(URI endSessionEndpoint) {
        this.end_session_endpoint = endSessionEndpoint;
    }

    public DiscoveryDocumentDto endSessionEndpoint(URI endSessionEndpoint) {
        this.end_session_endpoint = endSessionEndpoint;
        return this;
    }

    /**
     * Get jwks_uri
     * @return jwks_uri
     */
    public URI getJwksUri() {
        return jwks_uri;
    }

    public void setJwksUri(URI jwksUri) {
        this.jwks_uri = jwksUri;
    }

    public DiscoveryDocumentDto jwksUri(URI jwksUri) {
        this.jwks_uri = jwksUri;
        return this;
    }

    public <T> DiscoveryDocumentDto grantTypesSupported(Collection<T> items, Function<T, GrantTypeDto> mapper) {
        return grantTypesSupported(items.stream().map(mapper).collect(Collectors.toSet()));
    }

    public <T> Set<T> getGrantTypesSupported(Function<GrantTypeDto, T> mapper) {
        return getGrantTypesSupported().stream().map(mapper).collect(Collectors.toSet());
    }

    public DiscoveryDocumentDto addGrantTypesSupportedItem(GrantTypeDto grantTypesSupportedItem) {
        if (this.grant_types_supported == null) {
            this.grant_types_supported = new LinkedHashSet<>();
        }
        this.grant_types_supported.add(grantTypesSupportedItem);
        return this;
    }

    /**
     * Get grant_types_supported
     * @return grant_types_supported
     */
    public Set<GrantTypeDto> getGrantTypesSupported() {
        return grant_types_supported;
    }

    public void setGrantTypesSupported(Set<GrantTypeDto> grantTypesSupported) {
        this.grant_types_supported = grantTypesSupported;
    }

    public DiscoveryDocumentDto grantTypesSupported(Set<GrantTypeDto> grantTypesSupported) {
        this.grant_types_supported = grantTypesSupported;
        return this;
    }

    public <T> DiscoveryDocumentDto scopesSupported(Collection<T> items, Function<T, String> mapper) {
        return scopesSupported(items.stream().map(mapper).collect(Collectors.toSet()));
    }

    public <T> Set<T> getScopesSupported(Function<String, T> mapper) {
        return getScopesSupported().stream().map(mapper).collect(Collectors.toSet());
    }

    public DiscoveryDocumentDto addScopesSupportedItem(String scopesSupportedItem) {
        if (this.scopes_supported == null) {
            this.scopes_supported = new LinkedHashSet<>();
        }
        this.scopes_supported.add(scopesSupportedItem);
        return this;
    }

    /**
     * Get scopes_supported
     * @return scopes_supported
     */
    public Set<String> getScopesSupported() {
        return scopes_supported;
    }

    public void setScopesSupported(Set<String> scopesSupported) {
        this.scopes_supported = scopesSupported;
    }

    public DiscoveryDocumentDto scopesSupported(Set<String> scopesSupported) {
        this.scopes_supported = scopesSupported;
        return this;
    }

    public <T> DiscoveryDocumentDto claimsSupported(Collection<T> items, Function<T, String> mapper) {
        return claimsSupported(items.stream().map(mapper).collect(Collectors.toSet()));
    }

    public <T> Set<T> getClaimsSupported(Function<String, T> mapper) {
        return getClaimsSupported().stream().map(mapper).collect(Collectors.toSet());
    }

    public DiscoveryDocumentDto addClaimsSupportedItem(String claimsSupportedItem) {
        if (this.claims_supported == null) {
            this.claims_supported = new LinkedHashSet<>();
        }
        this.claims_supported.add(claimsSupportedItem);
        return this;
    }

    /**
     * Get claims_supported
     * @return claims_supported
     */
    public Set<String> getClaimsSupported() {
        return claims_supported;
    }

    public void setClaimsSupported(Set<String> claimsSupported) {
        this.claims_supported = claimsSupported;
    }

    public DiscoveryDocumentDto claimsSupported(Set<String> claimsSupported) {
        this.claims_supported = claimsSupported;
        return this;
    }

    public <T> DiscoveryDocumentDto responseTypesSupported(Collection<T> items, Function<T, ResponseTypeDto> mapper) {
        return responseTypesSupported(items.stream().map(mapper).collect(Collectors.toSet()));
    }

    public <T> Set<T> getResponseTypesSupported(Function<ResponseTypeDto, T> mapper) {
        return getResponseTypesSupported().stream().map(mapper).collect(Collectors.toSet());
    }

    public DiscoveryDocumentDto addResponseTypesSupportedItem(ResponseTypeDto responseTypesSupportedItem) {
        this.response_types_supported.add(responseTypesSupportedItem);
        return this;
    }

    /**
     * Get response_types_supported
     * @return response_types_supported
     */
    public Set<ResponseTypeDto> getResponseTypesSupported() {
        return response_types_supported;
    }

    public void setResponseTypesSupported(Set<ResponseTypeDto> responseTypesSupported) {
        this.response_types_supported = responseTypesSupported;
    }

    public DiscoveryDocumentDto responseTypesSupported(Set<ResponseTypeDto> responseTypesSupported) {
        this.response_types_supported = responseTypesSupported;
        return this;
    }

    public <T> DiscoveryDocumentDto responseModesSupported(Collection<T> items, Function<T, ResponseModesSupportedEnum> mapper) {
        return responseModesSupported(items.stream().map(mapper).collect(Collectors.toSet()));
    }

    public <T> Set<T> getResponseModesSupported(Function<ResponseModesSupportedEnum, T> mapper) {
        return getResponseModesSupported().stream().map(mapper).collect(Collectors.toSet());
    }

    public DiscoveryDocumentDto addResponseModesSupportedItem(ResponseModesSupportedEnum responseModesSupportedItem) {
        if (this.response_modes_supported == null) {
            this.response_modes_supported = new LinkedHashSet<>();
        }
        this.response_modes_supported.add(responseModesSupportedItem);
        return this;
    }

    /**
     * Get response_modes_supported
     * @return response_modes_supported
     */
    public Set<ResponseModesSupportedEnum> getResponseModesSupported() {
        return response_modes_supported;
    }

    public void setResponseModesSupported(Set<ResponseModesSupportedEnum> responseModesSupported) {
        this.response_modes_supported = responseModesSupported;
    }

    public DiscoveryDocumentDto responseModesSupported(Set<ResponseModesSupportedEnum> responseModesSupported) {
        this.response_modes_supported = responseModesSupported;
        return this;
    }

    public <T> DiscoveryDocumentDto subjectTypesSupported(Collection<T> items, Function<T, SubjectTypesSupportedEnum> mapper) {
        return subjectTypesSupported(items.stream().map(mapper).collect(Collectors.toSet()));
    }

    public <T> Set<T> getSubjectTypesSupported(Function<SubjectTypesSupportedEnum, T> mapper) {
        return getSubjectTypesSupported().stream().map(mapper).collect(Collectors.toSet());
    }

    public DiscoveryDocumentDto addSubjectTypesSupportedItem(SubjectTypesSupportedEnum subjectTypesSupportedItem) {
        if (this.subject_types_supported == null) {
            this.subject_types_supported = new LinkedHashSet<>();
        }
        this.subject_types_supported.add(subjectTypesSupportedItem);
        return this;
    }

    /**
     * Get subject_types_supported
     * @return subject_types_supported
     */
    public Set<SubjectTypesSupportedEnum> getSubjectTypesSupported() {
        return subject_types_supported;
    }

    public void setSubjectTypesSupported(Set<SubjectTypesSupportedEnum> subjectTypesSupported) {
        this.subject_types_supported = subjectTypesSupported;
    }

    public DiscoveryDocumentDto subjectTypesSupported(Set<SubjectTypesSupportedEnum> subjectTypesSupported) {
        this.subject_types_supported = subjectTypesSupported;
        return this;
    }

    public <T> DiscoveryDocumentDto codeChallengeMethodsSupported(Collection<T> items, Function<T, CodeChallengeMethodsSupportedEnum> mapper) {
        return codeChallengeMethodsSupported(items.stream().map(mapper).collect(Collectors.toSet()));
    }

    public <T> Set<T> getCodeChallengeMethodsSupported(Function<CodeChallengeMethodsSupportedEnum, T> mapper) {
        return getCodeChallengeMethodsSupported().stream().map(mapper).collect(Collectors.toSet());
    }

    public DiscoveryDocumentDto addCodeChallengeMethodsSupportedItem(CodeChallengeMethodsSupportedEnum codeChallengeMethodsSupportedItem) {
        if (this.code_challenge_methods_supported == null) {
            this.code_challenge_methods_supported = new LinkedHashSet<>();
        }
        this.code_challenge_methods_supported.add(codeChallengeMethodsSupportedItem);
        return this;
    }

    /**
     * Get code_challenge_methods_supported
     * @return code_challenge_methods_supported
     */
    public Set<CodeChallengeMethodsSupportedEnum> getCodeChallengeMethodsSupported() {
        return code_challenge_methods_supported;
    }

    public void setCodeChallengeMethodsSupported(Set<CodeChallengeMethodsSupportedEnum> codeChallengeMethodsSupported) {
        this.code_challenge_methods_supported = codeChallengeMethodsSupported;
    }

    public DiscoveryDocumentDto codeChallengeMethodsSupported(Set<CodeChallengeMethodsSupportedEnum> codeChallengeMethodsSupported) {
        this.code_challenge_methods_supported = codeChallengeMethodsSupported;
        return this;
    }

    public <T> DiscoveryDocumentDto idTokenSigningAlgValuesSupported(Collection<T> items, Function<T, IdTokenSigningAlgValuesSupportedEnum> mapper) {
        return idTokenSigningAlgValuesSupported(items.stream().map(mapper).collect(Collectors.toList()));
    }

    public <T> List<T> getIdTokenSigningAlgValuesSupported(Function<IdTokenSigningAlgValuesSupportedEnum, T> mapper) {
        return getIdTokenSigningAlgValuesSupported().stream().map(mapper).collect(Collectors.toList());
    }

    public DiscoveryDocumentDto addIdTokenSigningAlgValuesSupportedItem(IdTokenSigningAlgValuesSupportedEnum idTokenSigningAlgValuesSupportedItem) {
        if (this.id_token_signing_alg_values_supported == null) {
            this.id_token_signing_alg_values_supported = new ArrayList<>();
        }
        this.id_token_signing_alg_values_supported.add(idTokenSigningAlgValuesSupportedItem);
        return this;
    }

    /**
     * Get id_token_signing_alg_values_supported
     * @return id_token_signing_alg_values_supported
     */
    public List<IdTokenSigningAlgValuesSupportedEnum> getIdTokenSigningAlgValuesSupported() {
        return id_token_signing_alg_values_supported;
    }

    public void setIdTokenSigningAlgValuesSupported(List<IdTokenSigningAlgValuesSupportedEnum> idTokenSigningAlgValuesSupported) {
        this.id_token_signing_alg_values_supported = idTokenSigningAlgValuesSupported;
    }

    public DiscoveryDocumentDto idTokenSigningAlgValuesSupported(List<IdTokenSigningAlgValuesSupportedEnum> idTokenSigningAlgValuesSupported) {
        this.id_token_signing_alg_values_supported = idTokenSigningAlgValuesSupported;
        return this;
    }

    /**
     * Get x_sso_frame
     * @return x_sso_frame
     */
    public String getxSsoFrame() {
        return x_sso_frame;
    }

    public void setxSsoFrame(String xSsoFrame) {
        this.x_sso_frame = xSsoFrame;
    }

    public DiscoveryDocumentDto xSsoFrame(String xSsoFrame) {
        this.x_sso_frame = xSsoFrame;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DiscoveryDocumentDto discoveryDocument = (DiscoveryDocumentDto) o;
        return Objects.equals(this.getIssuer(), discoveryDocument.getIssuer()) &&
                Objects.equals(this.getAuthorizationEndpoint(), discoveryDocument.getAuthorizationEndpoint()) &&
                Objects.equals(this.getTokenEndpoint(), discoveryDocument.getTokenEndpoint()) &&
                Objects.equals(this.getUserinfoEndpoint(), discoveryDocument.getUserinfoEndpoint()) &&
                Objects.equals(this.getEndSessionEndpoint(), discoveryDocument.getEndSessionEndpoint()) &&
                Objects.equals(this.getJwksUri(), discoveryDocument.getJwksUri()) &&
                Objects.equals(this.getGrantTypesSupported(), discoveryDocument.getGrantTypesSupported()) &&
                Objects.equals(this.getScopesSupported(), discoveryDocument.getScopesSupported()) &&
                Objects.equals(this.getClaimsSupported(), discoveryDocument.getClaimsSupported()) &&
                Objects.equals(this.getResponseTypesSupported(), discoveryDocument.getResponseTypesSupported()) &&
                Objects.equals(this.getResponseModesSupported(), discoveryDocument.getResponseModesSupported()) &&
                Objects.equals(this.getSubjectTypesSupported(), discoveryDocument.getSubjectTypesSupported()) &&
                Objects.equals(this.getCodeChallengeMethodsSupported(), discoveryDocument.getCodeChallengeMethodsSupported()) &&
                Objects.equals(this.getIdTokenSigningAlgValuesSupported(), discoveryDocument.getIdTokenSigningAlgValuesSupported()) &&
                Objects.equals(this.getxSsoFrame(), discoveryDocument.getxSsoFrame());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIssuer(), getAuthorizationEndpoint(), getTokenEndpoint(), getUserinfoEndpoint(), getEndSessionEndpoint(), getJwksUri(), getGrantTypesSupported(), getScopesSupported(), getClaimsSupported(), getResponseTypesSupported(), getResponseModesSupported(), getSubjectTypesSupported(), getCodeChallengeMethodsSupported(), getIdTokenSigningAlgValuesSupported(), getxSsoFrame());
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("DiscoveryDocumentDto {\n");
        sb.append("    issuer: ").append(toIndentedString(getIssuer())).append("\n");
        sb.append("    authorization_endpoint: ").append(toIndentedString(getAuthorizationEndpoint())).append("\n");
        sb.append("    token_endpoint: ").append(toIndentedString(getTokenEndpoint())).append("\n");
        sb.append("    userinfo_endpoint: ").append(toIndentedString(getUserinfoEndpoint())).append("\n");
        sb.append("    end_session_endpoint: ").append(toIndentedString(getEndSessionEndpoint())).append("\n");
        sb.append("    jwks_uri: ").append(toIndentedString(getJwksUri())).append("\n");
        sb.append("    grant_types_supported: ").append(toIndentedString(getGrantTypesSupported())).append("\n");
        sb.append("    scopes_supported: ").append(toIndentedString(getScopesSupported())).append("\n");
        sb.append("    claims_supported: ").append(toIndentedString(getClaimsSupported())).append("\n");
        sb.append("    response_types_supported: ").append(toIndentedString(getResponseTypesSupported())).append("\n");
        sb.append("    response_modes_supported: ").append(toIndentedString(getResponseModesSupported())).append("\n");
        sb.append("    subject_types_supported: ").append(toIndentedString(getSubjectTypesSupported())).append("\n");
        sb.append("    code_challenge_methods_supported: ").append(toIndentedString(getCodeChallengeMethodsSupported())).append("\n");
        sb.append("    id_token_signing_alg_values_supported: ").append(toIndentedString(getIdTokenSigningAlgValuesSupported())).append("\n");
        sb.append("    x_sso_frame: ").append(toIndentedString(getxSsoFrame())).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

