/*
 * FakeRESTApi.Web V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.fakerestapi.api;

import io.github.jhannes.openapi.fakerestapi.ApiException;
import io.github.jhannes.openapi.fakerestapi.model.ActivityDto;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ActivitiesApi
 */
public class ActivitiesApiTest {

    private final ActivitiesApi api = new ActivitiesApi();

    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1ActivitiesGetTest() throws ApiException {
        //
        //List<ActivityDto> response = api.apiV1ActivitiesGet();

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1ActivitiesIdDeleteTest() throws ApiException {
        //
        //Integer id = null;
        //
        //api.apiV1ActivitiesIdDelete(id);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1ActivitiesIdGetTest() throws ApiException {
        //
        //Integer id = null;
        //
        //List<ActivityDto> response = api.apiV1ActivitiesIdGet(id);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1ActivitiesIdPutTest() throws ApiException {
        //
        //Integer id = null;
        //
        //ActivityDto activityDto = null;
        //
        //ActivityDto response = api.apiV1ActivitiesIdPut(id, activityDto);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1ActivitiesPostTest() throws ApiException {
        //
        //ActivityDto activityDto = null;
        //
        //ActivityDto response = api.apiV1ActivitiesPost(activityDto);

        // TODO: test validations
    }
}
