/*
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key \"special-key\" to test the authorization filters
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.petstore.api;

import java.io.File;
import io.github.jhannes.openapi.petstore.model.PetDto;
import io.github.jhannes.openapi.petstore.model.SampleModelData;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.MalformedURLException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

/**
 * API tests for PetApi
 */
public class PetApiTest {

    private final PetApi api = new HttpPetApi();
    private final SampleModelData sampleData = new SampleModelData(-1);

    public PetApiTest() throws MalformedURLException {
    }

    @Test
    public void addPetTest() throws IOException {
        //PetDto petDto = null;
        //api.addPet(petDto);
        // TODO: test validations
    }

    @Test
    public void deletePetTest() throws IOException {
        //Long petId = null;
        //String apiKey = null;
        //api.deletePet(petId, apiKey);
        // TODO: test validations
    }

    @Test
    public void downloadImageTest() throws IOException {
        //Long petId = null;
        //File response = api.downloadImage(petId);
        // TODO: test validations
    }

    @Test
    public void findPetsByStatusTest() throws IOException {
        //List<String> status = null;
        //List<PetDto> response = api.findPetsByStatus(status);
        // TODO: test validations
    }

    @Test
    public void findPetsByTagsTest() throws IOException {
        //List<String> tags = null;
        //List<PetDto> response = api.findPetsByTags(tags);
        // TODO: test validations
    }

    @Test
    public void getPetByIdTest() throws IOException {
        //Long petId = null;
        //PetDto response = api.getPetById(petId);
        // TODO: test validations
    }

    @Test
    public void updatePetTest() throws IOException {
        //PetDto petDto = null;
        //api.updatePet(petDto);
        // TODO: test validations
    }

    @Test
    public void updatePetWithFormTest() throws IOException {
        //String petId = null;
        //String name = null;
        //String status = null;
        //api.updatePetWithForm(petId, name, status);
        // TODO: test validations
    }

    @Test
    public void uploadFileTest() throws IOException {
        //Long petId = null;
        //String additionalMetadata = null;
        //File _file = null;
        //api.uploadFile(petId, additionalMetadata, _file);
        // TODO: test validations
    }

}
