/*
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key \"special-key\" to test the authorization filters
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.petstore.api;

import java.time.OffsetDateTime;
import io.github.jhannes.openapi.petstore.model.OrderDto;
import io.github.jhannes.openapi.petstore.model.SampleModelData;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.MalformedURLException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

/**
 * API tests for StoreApi
 */
public class StoreApiTest {

    private final StoreApi api = new HttpStoreApi();
    private final SampleModelData sampleData = new SampleModelData(-1);

    public StoreApiTest() throws MalformedURLException {
    }

    @Test
    public void deleteOrderTest() throws IOException {
        //String orderId = null;
        //api.deleteOrder(orderId);
        // TODO: test validations
    }

    @Test
    public void getInventoryTest() throws IOException {
        //OffsetDateTime effectiveDateTime = null;
        //Map<String, Integer> response = api.getInventory(effectiveDateTime);
        // TODO: test validations
    }

    @Test
    public void getOrderByIdTest() throws IOException {
        //String orderId = null;
        //OrderDto response = api.getOrderById(orderId);
        // TODO: test validations
    }

    @Test
    public void placeOrderTest() throws IOException {
        //OrderDto orderDto = null;
        //OrderDto response = api.placeOrder(orderDto);
        // TODO: test validations
    }

}
