/*
 * Infection Tracker
 * Infection Tracker - A case management system for tracking the spread of diseases
 *
 * The version of the OpenAPI document: 1.0.0-draft
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.jhannes.openapi.infectionTracker.api;

import io.github.jhannes.openapi.infectionTracker.model.CaseWorkerDto;
import io.github.jhannes.openapi.infectionTracker.model.SampleModelData;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.MalformedURLException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

/**
 * API tests for CaseWorkersApi
 */
public class CaseWorkersApiTest {

    private final CaseWorkersApi api = new HttpCaseWorkersApi();
    private final SampleModelData sampleData = new SampleModelData(-1);

    public CaseWorkersApiTest() throws MalformedURLException {
    }

    @Test
    public void listCaseWorkersTest() throws IOException {
        //CaseWorkerDto response = api.listCaseWorkers();
        // TODO: test validations
    }

    @Test
    public void registerCaseWorkerTest() throws IOException {
        //CaseWorkerDto caseWorkerDto = null;
        //api.registerCaseWorker(caseWorkerDto);
        // TODO: test validations
    }

}
